"""test

Revision ID: 007e3a5adf8e
Revises: 1caa0ce0be89
Create Date: 2023-12-17 17:23:11.375136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '007e3a5adf8e'
down_revision = '1caa0ce0be89'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_viewing')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_viewing', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
