"""Added the AdditionalInfo

Revision ID: 061174cf7daa
Revises: 3ba323b7f113
Create Date: 2023-12-19 14:12:02.677165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '061174cf7daa'
down_revision = '3ba323b7f113'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('additional_info', sa.Column('value', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'additional_info', ['name'])
    op.drop_column('additional_info', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('additional_info', sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'additional_info', type_='unique')
    op.drop_column('additional_info', 'value')
    # ### end Alembic commands ###
