"""test

Revision ID: 0fade32e8e4a
Revises: 7cf2e9bc2ee2
Create Date: 2023-12-17 17:22:25.574695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fade32e8e4a'
down_revision = '7cf2e9bc2ee2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_viewing')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_viewing', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
