"""test

Revision ID: 1caa0ce0be89
Revises: 0fade32e8e4a
Create Date: 2023-12-17 17:22:36.079932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1caa0ce0be89'
down_revision = '0fade32e8e4a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_viewing', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_viewing')
    # ### end Alembic commands ###
