"""added monita start

Revision ID: 3ba323b7f113
Revises: 923f9d419f6f
Create Date: 2023-12-18 20:40:39.710801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ba323b7f113'
down_revision = '923f9d419f6f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
