"""Added new models

Revision ID: 4de18065d472
Revises: 1e862d99e013
Create Date: 2023-12-05 16:32:02.891105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4de18065d472'
down_revision = '1e862d99e013'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monita_date_type', sa.Column('budget', sa.Integer(), nullable=True))
    op.add_column('monita_date_type', sa.Column('orderIndex', sa.Integer(), nullable=True))
    op.drop_constraint('monita_date_type_giftReciever_fkey', 'monita_date_type', type_='foreignkey')
    op.drop_column('monita_date_type', 'giftReciever')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monita_date_type', sa.Column('giftReciever', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('monita_date_type_giftReciever_fkey', 'monita_date_type', 'users', ['giftReciever'], ['id'])
    op.drop_column('monita_date_type', 'orderIndex')
    op.drop_column('monita_date_type', 'budget')
    # ### end Alembic commands ###
