"""Changed column name

Revision ID: 5ffe73ce5b8d
Revises: ef07dd41015b
Create Date: 2023-12-07 17:37:25.498310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ffe73ce5b8d'
down_revision = 'ef07dd41015b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'monita', ['receiver_id'])
    op.create_unique_constraint(None, 'monita', ['sender_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'monita', type_='unique')
    op.drop_constraint(None, 'monita', type_='unique')
    # ### end Alembic commands ###
