"""Added a new column to the BudgetSpend

Revision ID: 65579420fe22
Revises: 70fb1b16b9c0
Create Date: 2023-12-11 10:26:17.539448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65579420fe22'
down_revision = '70fb1b16b9c0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budget_spend', sa.Column('is_send', sa.Boolean(), nullable=True))
    op.add_column('budget_spend', sa.Column('is_received', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('budget_spend', 'is_received')
    op.drop_column('budget_spend', 'is_send')
    # ### end Alembic commands ###
