"""Migrate

Revision ID: 677e7363fc07
Revises: 9d565a60d0c1
Create Date: 2023-12-05 14:34:15.910902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '677e7363fc07'
down_revision = '9d565a60d0c1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'roles', ['role'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
