"""added new columns to the useres

Revision ID: 7a94049b76b6
Revises: d69e1b7333ef
Create Date: 2023-12-17 16:23:28.561512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a94049b76b6'
down_revision = 'd69e1b7333ef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_selected', sa.Boolean()))
    op.add_column('users', sa.Column('is_viewing', sa.Boolean()))
    # ### end Alembic commands ###
    

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_viewing')
    op.drop_column('users', 'is_selected')
    # ### end Alembic commands ###
