"""added new columns to the useres

Revision ID: 7cf2e9bc2ee2
Revises: dea5f4354d68
Create Date: 2023-12-17 17:19:29.928856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cf2e9bc2ee2'
down_revision = 'dea5f4354d68'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_viewing',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_viewing',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
