"""isMonitaRevealed model

Revision ID: 7dfed4e69d34
Revises: efa21a4051dd
Create Date: 2023-12-18 14:13:29.661538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dfed4e69d34'
down_revision = 'efa21a4051dd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
