"""Changed column name

Revision ID: 8879b4ee3f00
Revises: b6061c251cb5
Create Date: 2023-12-07 09:45:36.012115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8879b4ee3f00'
down_revision = 'b6061c251cb5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monita', sa.Column('receiver_id', sa.Integer(), nullable=True))
    op.drop_constraint('monita_reciever_id_fkey', 'monita', type_='foreignkey')
    op.create_foreign_key(None, 'monita', 'users', ['receiver_id'], ['id'])
    op.drop_column('monita', 'reciever_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monita', sa.Column('reciever_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'monita', type_='foreignkey')
    op.create_foreign_key('monita_reciever_id_fkey', 'monita', 'users', ['reciever_id'], ['id'])
    op.drop_column('monita', 'receiver_id')
    # ### end Alembic commands ###
