"""added viewed count

Revision ID: 923f9d419f6f
Revises: 19a8af8d2f89
Create Date: 2023-12-18 17:59:19.021321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '923f9d419f6f'
down_revision = '19a8af8d2f89'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('viewed_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'viewed_count')
    # ### end Alembic commands ###
