"""Added is_active column to the Users model

Revision ID: 93900296e7e9
Revises: 4bf7ab50a608
Create Date: 2023-12-13 09:36:28.871491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93900296e7e9'
down_revision = '4bf7ab50a608'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
