"""Added new models

Revision ID: 95f8e3b01e40
Revises: 4de18065d472
Create Date: 2023-12-05 16:38:30.728849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95f8e3b01e40'
down_revision = '4de18065d472'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budget_spend', sa.Column('sender_id', sa.Integer(), nullable=True))
    op.add_column('budget_spend', sa.Column('reciever_id', sa.Integer(), nullable=True))
    op.add_column('budget_spend', sa.Column('monitaDateType_id', sa.Integer(), nullable=True))
    op.drop_constraint('budget_spend_user_fkey', 'budget_spend', type_='foreignkey')
    op.drop_constraint('budget_spend_receivedUser_fkey', 'budget_spend', type_='foreignkey')
    op.create_foreign_key(None, 'budget_spend', 'monita_date_type', ['monitaDateType_id'], ['id'])
    op.create_foreign_key(None, 'budget_spend', 'users', ['reciever_id'], ['id'])
    op.create_foreign_key(None, 'budget_spend', 'users', ['sender_id'], ['id'])
    op.drop_column('budget_spend', 'receivedUser')
    op.drop_column('budget_spend', 'user')
    op.add_column('monita', sa.Column('sender_id', sa.Integer(), nullable=True))
    op.add_column('monita', sa.Column('reciever_id', sa.Integer(), nullable=True))
    op.drop_constraint('monita_giftSender_fkey', 'monita', type_='foreignkey')
    op.drop_constraint('monita_giftReciever_fkey', 'monita', type_='foreignkey')
    op.create_foreign_key(None, 'monita', 'users', ['reciever_id'], ['id'])
    op.create_foreign_key(None, 'monita', 'users', ['sender_id'], ['id'])
    op.drop_column('monita', 'giftReciever')
    op.drop_column('monita', 'giftSender')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monita', sa.Column('giftSender', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('monita', sa.Column('giftReciever', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'monita', type_='foreignkey')
    op.drop_constraint(None, 'monita', type_='foreignkey')
    op.create_foreign_key('monita_giftReciever_fkey', 'monita', 'users', ['giftReciever'], ['id'])
    op.create_foreign_key('monita_giftSender_fkey', 'monita', 'users', ['giftSender'], ['id'])
    op.drop_column('monita', 'reciever_id')
    op.drop_column('monita', 'sender_id')
    op.add_column('budget_spend', sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('budget_spend', sa.Column('receivedUser', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'budget_spend', type_='foreignkey')
    op.drop_constraint(None, 'budget_spend', type_='foreignkey')
    op.drop_constraint(None, 'budget_spend', type_='foreignkey')
    op.create_foreign_key('budget_spend_receivedUser_fkey', 'budget_spend', 'users', ['receivedUser'], ['id'])
    op.create_foreign_key('budget_spend_user_fkey', 'budget_spend', 'users', ['user'], ['id'])
    op.drop_column('budget_spend', 'monitaDateType_id')
    op.drop_column('budget_spend', 'reciever_id')
    op.drop_column('budget_spend', 'sender_id')
    # ### end Alembic commands ###
