"""added new columns 

Revision ID: 988096907462
Revises: 5ffe73ce5b8d
Create Date: 2023-12-08 18:53:34.607509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '988096907462'
down_revision = '5ffe73ce5b8d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('occupation', sa.String(), server_default='Test', nullable=False))
    op.add_column('users', sa.Column('department', sa.String(), server_default='Test', nullable=False))
    op.add_column('users', sa.Column('division', sa.String(), server_default='Test', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'division')
    op.drop_column('users', 'department')
    op.drop_column('users', 'occupation')
    # ### end Alembic commands ###
