"""Migrate

Revision ID: 9d565a60d0c1
Revises: 39a476585b9f
Create Date: 2023-12-05 14:01:37.934974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d565a60d0c1'
down_revision = '39a476585b9f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profileImage', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profileImage')
    # ### end Alembic commands ###
