"""added sms_response_2

Revision ID: acd5104f52bf
Revises: d9a8bda8d636
Create Date: 2023-12-21 08:46:04.554592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acd5104f52bf'
down_revision = 'd9a8bda8d636'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sms_response_2', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sms_response_2')
    # ### end Alembic commands ###
