"""Added a new column to the BudgetSpen

Revision ID: b013980d9871
Revises: 1b2672807887
Create Date: 2023-12-11 10:52:30.969417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b013980d9871'
down_revision = '1b2672807887'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budget_spend', sa.Column('receiver_id', sa.Integer(), nullable=False))
    op.drop_constraint('budget_spend_reciever_id_fkey', 'budget_spend', type_='foreignkey')
    op.create_foreign_key(None, 'budget_spend', 'users', ['receiver_id'], ['id'])
    op.drop_column('budget_spend', 'reciever_id')
    op.alter_column('monita', 'sender_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('monita', 'receiver_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('monita', 'receiver_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('monita', 'sender_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('budget_spend', sa.Column('reciever_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'budget_spend', type_='foreignkey')
    op.create_foreign_key('budget_spend_reciever_id_fkey', 'budget_spend', 'users', ['reciever_id'], ['id'])
    op.drop_column('budget_spend', 'receiver_id')
    # ### end Alembic commands ###
