"""Added type column to the MonitaDateType model

Revision ID: d69e1b7333ef
Revises: 619a9ab813df
Create Date: 2023-12-13 15:46:20.117444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd69e1b7333ef'
down_revision = '619a9ab813df'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monita_date_type', sa.Column('type', sa.String(), server_default='MAIN', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monita_date_type', 'type')
    # ### end Alembic commands ###
