"""added new columns to the users

Revision ID: dea5f4354d68
Revises: 7a94049b76b6
Create Date: 2023-12-17 16:27:06.618929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dea5f4354d68'
down_revision = '7a94049b76b6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_selected',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'is_viewing',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_viewing',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_selected',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
